<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Health.Direct.Context.Loopback.Receiver.tests</RootNamespace>
    <AssemblyName>Health.Direct.Context.Loopback.Receiver.tests</AssemblyName>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Interop.CDO">
      <HintPath>..\build\libraries\smtpagent_com_interop\Interop.CDO.dll</HintPath>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </Reference>
    <Reference Include="System.Security" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <None Update="ContextTestFiles\BadContext\ContextMissing.eml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContextTestFiles\BadContext\ContextUnparsablePatient.eml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContextTestFiles\BadContext\ContextUnparsableType.eml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContextTestFiles\BadContext\DSN.eml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContextTestFiles\BadContext\MDN.eml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContextTestFiles\BadContext\NoDirectContextHeader.eml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContextTestFiles\ContextHL7.Default.txtBase64">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContextTestFiles\ContextSimple.PatienIdOnly.txtDefault">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContextTestFiles\ContextSimple1.txtBase64">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContextTestFiles\ContextSimple1.txtBinary">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContextTestFiles\ContextSimple1.txtDefault">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContextTestFiles\ContextSimple1.txtEightBit">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContextTestFiles\ContextSimple1.txtQuotedPrintable">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContextTestFiles\ContextSimple1.txtSevenBit">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContextTestFiles\ContextSimple1.txtUUEncode">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\agent\agent.csproj" />
    <ProjectReference Include="..\common\common.csproj" />
    <ProjectReference Include="..\context.receiver\context.loopback.receiver.csproj" />
    <ProjectReference Include="..\diagnostics\diagnostics.nlog.csproj" />
    <ProjectReference Include="..\gateway\smtpAgent\smtpAgent.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
  </ItemGroup>
  <ItemGroup>
	  <PackageReference Include="MimeKit" Version="4.13.0" />
    <PackageReference Include="NLog" Version="1.0.0.505" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.abstractions" Version="2.0.3" />
    <PackageReference Include="xunit.assert" Version="2.9.3" />
    <PackageReference Include="xunit.core" Version="2.9.3" />
    <PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
    <PackageReference Include="xunit.extensibility.execution" Version="2.9.3" />
  </ItemGroup>
</Project>