//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Health.Direct.Config.Client.AuthManagerService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Administrator", Namespace="urn:directproject:config/store/082010")]
    public partial class Administrator : object
    {
        
        private System.DateTime CreateDateField;
        
        private long IDField;
        
        private Health.Direct.Config.Client.AuthManagerService.PasswordHash PasswordHashField;
        
        private Health.Direct.Config.Client.AuthManagerService.EntityStatus StatusField;
        
        private System.DateTime UpdateDateField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Health.Direct.Config.Client.AuthManagerService.PasswordHash PasswordHash
        {
            get
            {
                return this.PasswordHashField;
            }
            set
            {
                this.PasswordHashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Health.Direct.Config.Client.AuthManagerService.EntityStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime UpdateDate
        {
            get
            {
                return this.UpdateDateField;
            }
            set
            {
                this.UpdateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordHash", Namespace="http://schemas.datacontract.org/2004/07/Health.Direct.Config.Store")]
    public partial class PasswordHash : object
    {
        
        private string HashedPasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string HashedPassword
        {
            get
            {
                return this.HashedPasswordField;
            }
            set
            {
                this.HashedPasswordField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityStatus", Namespace="http://schemas.datacontract.org/2004/07/Health.Direct.Config.Store")]
    public enum EntityStatus : byte
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enabled = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigStoreFault", Namespace="urn:directproject:config/store/082010")]
    public partial class ConfigStoreFault : object
    {
        
        private Health.Direct.Config.Client.AuthManagerService.ConfigStoreError ErrorField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Health.Direct.Config.Client.AuthManagerService.ConfigStoreError Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigStoreError", Namespace="http://schemas.datacontract.org/2004/07/Health.Direct.Config.Store")]
    public enum ConfigStoreError : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unexpected = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Conflict = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UniqueConstraint = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ForeignKeyConstraint = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidIDs = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidDomain = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidDomainName = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DomainNameLength = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidDomainID = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidAddress = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddressLength = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DisplayNameLength = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailAddress = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCertificate = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidX509Certificate = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingCertificateData = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidOwnerName = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OwnerLength = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidThumbprint = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidAnchor = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountNameLength = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMXSMTPName = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MXSMTPNameLength = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMX = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidDnsRecord = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotesLength = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidAdministrator = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUsername = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPassword = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPropertyName = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPropertyNameLength = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidTextBlobName = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidTextBlobNameLength = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidBlob = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AgentNameLength = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidAgentName = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMdnIdentifier = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMdn = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateProcessedMdn = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateDispatchedMdn = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateFailedMdn = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MdnPreviouslyProcessed = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MdnUncorrelated = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MdnPreviouslyFailed = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUrl = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UrlLength = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidBundle = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateMdnStart = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCertPolicyName = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CertPolicyNameLength = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingCertPolicyData = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCertPolicy = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCertPolicyGroupName = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCertPolicyGroup = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CertPolicyGroupDescriptionLength = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCertPolicyUse = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingDomain = 59,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:directproject:config/store/082010", ConfigurationName="Health.Direct.Config.Client.AuthManagerService.IAuthManager")]
    public interface IAuthManager
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:directproject:config/store/082010/IAuthManager/GetUser", ReplyAction="urn:directproject:config/store/082010/IAuthManager/GetUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Health.Direct.Config.Client.AuthManagerService.ConfigStoreFault), Action="urn:directproject:config/store/082010/IAuthManager/GetUserConfigStoreFaultFault", Name="ConfigStoreFault")]
        Health.Direct.Config.Client.AuthManagerService.GetUserResponse GetUser(Health.Direct.Config.Client.AuthManagerService.GetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:directproject:config/store/082010/IAuthManager/GetUser", ReplyAction="urn:directproject:config/store/082010/IAuthManager/GetUserResponse")]
        System.Threading.Tasks.Task<Health.Direct.Config.Client.AuthManagerService.GetUserResponse> GetUserAsync(Health.Direct.Config.Client.AuthManagerService.GetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:directproject:config/store/082010/IAuthManager/ValidateUser", ReplyAction="urn:directproject:config/store/082010/IAuthManager/ValidateUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Health.Direct.Config.Client.AuthManagerService.ConfigStoreFault), Action="urn:directproject:config/store/082010/IAuthManager/ValidateUserConfigStoreFaultFa" +
            "ult", Name="ConfigStoreFault")]
        Health.Direct.Config.Client.AuthManagerService.ValidateUserResponse ValidateUser(Health.Direct.Config.Client.AuthManagerService.ValidateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:directproject:config/store/082010/IAuthManager/ValidateUser", ReplyAction="urn:directproject:config/store/082010/IAuthManager/ValidateUserResponse")]
        System.Threading.Tasks.Task<Health.Direct.Config.Client.AuthManagerService.ValidateUserResponse> ValidateUserAsync(Health.Direct.Config.Client.AuthManagerService.ValidateUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUser", WrapperNamespace="urn:directproject:config/store/082010", IsWrapped=true)]
    public partial class GetUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:directproject:config/store/082010", Order=0)]
        public string username;
        
        public GetUserRequest()
        {
        }
        
        public GetUserRequest(string username)
        {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserResponse", WrapperNamespace="urn:directproject:config/store/082010", IsWrapped=true)]
    public partial class GetUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:directproject:config/store/082010", Order=0)]
        public Health.Direct.Config.Client.AuthManagerService.Administrator GetUserResult;
        
        public GetUserResponse()
        {
        }
        
        public GetUserResponse(Health.Direct.Config.Client.AuthManagerService.Administrator GetUserResult)
        {
            this.GetUserResult = GetUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateUser", WrapperNamespace="urn:directproject:config/store/082010", IsWrapped=true)]
    public partial class ValidateUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:directproject:config/store/082010", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:directproject:config/store/082010", Order=1)]
        public Health.Direct.Config.Client.AuthManagerService.PasswordHash passwordHash;
        
        public ValidateUserRequest()
        {
        }
        
        public ValidateUserRequest(string username, Health.Direct.Config.Client.AuthManagerService.PasswordHash passwordHash)
        {
            this.username = username;
            this.passwordHash = passwordHash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateUserResponse", WrapperNamespace="urn:directproject:config/store/082010", IsWrapped=true)]
    public partial class ValidateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:directproject:config/store/082010", Order=0)]
        public bool ValidateUserResult;
        
        public ValidateUserResponse()
        {
        }
        
        public ValidateUserResponse(bool ValidateUserResult)
        {
            this.ValidateUserResult = ValidateUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IAuthManagerChannel : Health.Direct.Config.Client.AuthManagerService.IAuthManager, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AuthManagerClient : System.ServiceModel.ClientBase<Health.Direct.Config.Client.AuthManagerService.IAuthManager>, Health.Direct.Config.Client.AuthManagerService.IAuthManager
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AuthManagerClient() : 
                base(AuthManagerClient.GetDefaultBinding(), AuthManagerClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAuthManager.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthManagerClient(EndpointConfiguration endpointConfiguration) : 
                base(AuthManagerClient.GetBindingForEndpoint(endpointConfiguration), AuthManagerClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthManagerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AuthManagerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthManagerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AuthManagerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Health.Direct.Config.Client.AuthManagerService.GetUserResponse GetUser(Health.Direct.Config.Client.AuthManagerService.GetUserRequest request)
        {
            return base.Channel.GetUser(request);
        }
        
        public System.Threading.Tasks.Task<Health.Direct.Config.Client.AuthManagerService.GetUserResponse> GetUserAsync(Health.Direct.Config.Client.AuthManagerService.GetUserRequest request)
        {
            return base.Channel.GetUserAsync(request);
        }
        
        public Health.Direct.Config.Client.AuthManagerService.ValidateUserResponse ValidateUser(Health.Direct.Config.Client.AuthManagerService.ValidateUserRequest request)
        {
            return base.Channel.ValidateUser(request);
        }
        
        public System.Threading.Tasks.Task<Health.Direct.Config.Client.AuthManagerService.ValidateUserResponse> ValidateUserAsync(Health.Direct.Config.Client.AuthManagerService.ValidateUserRequest request)
        {
            return base.Channel.ValidateUserAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuthManager))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuthManager))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:6692/AuthManagerService.svc/Authentication");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AuthManagerClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAuthManager);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AuthManagerClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAuthManager);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAuthManager,
        }
    }
}
