<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Health.Direct.Context.Loopback.Receiver</RootNamespace>
    <AssemblyName>Health.Direct.Context.Loopback.Receiver</AssemblyName>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Security" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\GlobalAssemblyInfo.cs">
      <Link>Properties\GlobalAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\agent\agent.csproj" />
    <ProjectReference Include="..\common\common.csproj" />
    <ProjectReference Include="..\diagnostics\diagnostics.nlog.csproj" />
    <ProjectReference Include="..\gateway\smtpAgent\smtpAgent.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DirectProject.DotNet.Context" Version="1.1.1-preview011" />
    <PackageReference Include="MimeKit" Version="4.13.0" />
  </ItemGroup>
</Project>